<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageProduct.aspx.cs" Inherits="RestaurantManagement.ManageProduct" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <%--<asp:GridView ID="GridView" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="GridView_RowDeleting" OnRowCreated="GridView_RowCreated"></asp:GridView>--%>
    
        <asp:GridView ID="gridView" runat="server" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Unit_Price" HeaderText="Unit_Price" SortExpression="Unit_Price" />
                <asp:BoundField DataField="Sale_Price" HeaderText="Sale_Price" SortExpression="Sale_Price" />
                <asp:CheckBoxField DataField="Status" HeaderText="Status" SortExpression="Status" />
                <asp:BoundField DataField="Image" ReadOnly="false" InsertVisible="False" HeaderText="Image" SortExpression="Image" />
                <asp:CommandField ShowEditButton="True" />
            </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DBCS %>" DeleteCommand="DELETE FROM [Product] WHERE [ID] = @original_ID AND (([Name] = @original_Name) OR ([Name] IS NULL AND @original_Name IS NULL)) AND (([Unit_Price] = @original_Unit_Price) OR ([Unit_Price] IS NULL AND @original_Unit_Price IS NULL)) AND (([Sale_Price] = @original_Sale_Price) OR ([Sale_Price] IS NULL AND @original_Sale_Price IS NULL)) AND (([Status] = @original_Status) OR ([Status] IS NULL AND @original_Status IS NULL)) AND (([Image] = @original_Image) OR ([Image] IS NULL AND @original_Image IS NULL))" InsertCommand="INSERT INTO [Product] ([Name], [Unit_Price], [Sale_Price], [Status], [Image]) VALUES (@Name, @Unit_Price, @Sale_Price, @Status, @Image)" SelectCommand="SELECT * FROM [Product]" UpdateCommand="UPDATE [Product] SET [Name] = @Name, [Unit_Price] = @Unit_Price, [Sale_Price] = @Sale_Price, [Status] = @Status, [Image] = @Image WHERE [ID] = @original_ID AND (([Name] = @original_Name) OR ([Name] IS NULL AND @original_Name IS NULL)) AND (([Unit_Price] = @original_Unit_Price) OR ([Unit_Price] IS NULL AND @original_Unit_Price IS NULL)) AND (([Sale_Price] = @original_Sale_Price) OR ([Sale_Price] IS NULL AND @original_Sale_Price IS NULL)) AND (([Status] = @original_Status) OR ([Status] IS NULL AND @original_Status IS NULL)) AND (([Image] = @original_Image) OR ([Image] IS NULL AND @original_Image IS NULL))" ConflictDetection="CompareAllValues" OldValuesParameterFormatString="original_{0}">
            <DeleteParameters>
                <asp:Parameter Name="original_ID" Type="Int32" />
                <asp:Parameter Name="original_Name" Type="String" />
                <asp:Parameter Name="original_Unit_Price" Type="Decimal" />
                <asp:Parameter Name="original_Sale_Price" Type="Decimal" />
                <asp:Parameter Name="original_Status" Type="Boolean" />
                <asp:Parameter Name="original_Image" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Unit_Price" Type="Decimal" />
                <asp:Parameter Name="Sale_Price" Type="Decimal" />
                <asp:Parameter Name="Status" Type="Boolean" />
                <asp:Parameter Name="Image" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Unit_Price" Type="Decimal" />
                <asp:Parameter Name="Sale_Price" Type="Decimal" />
                <asp:Parameter Name="Status" Type="Boolean" />
                <asp:Parameter Name="Image" Type="String" />
                <asp:Parameter Name="original_ID" Type="Int32" />
                <asp:Parameter Name="original_Name" Type="String" />
                <asp:Parameter Name="original_Unit_Price" Type="Decimal" />
                <asp:Parameter Name="original_Sale_Price" Type="Decimal" />
                <asp:Parameter Name="original_Status" Type="Boolean" />
                <asp:Parameter Name="original_Image" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>

        <asp:Button ID="back" runat="server" Text="Back" PostBackUrl="~/OrderWindow.aspx"/>
    </div>
    </form>
</body>
</html>
